### ISSUE TITLE
 Does Short-read Sequencing contains both DNA and RNA.

### ISSUE THREAD

**Issue by GeorgeBGM** [Hollenbach-lab/PING#7]
Dear Wesley,

It's really a useful software to analysis KIR region using Short-read Sequencing,so I am wandering if RNA-seq short reads can be used for KIR genotyping by PING.

I am looking forward for your reply.
Best,
Du

**Comment by wesleymarin** [comment]
Hello Du,

Unfortunately, we have not been able to make PING work for RNA-seq data. The reads are generally too short to provide good output information.

What does your RNA-seq data look like? And what kind of analysis are you hoping to get?

Thank you,
Wesley

**Comment by GeorgeBGM** [comment]
Dear Wesley,

The RNA-seq length is generated in illumina platform with reads length is 2x150bp, I want to perform genotype of KIR region based on RNA sequencig data.

Best,
Du

**Comment by wesleymarin** [comment]
The workflow is not setup for RNA-seq interpretation. I imagine it would require a significant overhaul of the alignment workflow.

My main concern with RNA-seq data is the read length sizes, but 2x150bp seems adequate. 

In summary, I think your data would work, but it would also take a significant amount of work and testing to get the workflow adapted for RNA-seq data, enough that it would warrant its own manuscript.

**Comment by GeorgeBGM** [comment]
Dear Wesley,

I think this would be a very meaningful work that could be used to do research on the immune genome(KIR,HLA,TCR) by RNA-seq.

What would you suggest about modifying the alignment workflow in PING to make it adaptable to RNA-seq data? In addition, does alternative RNA splicing affect subsequent genotype inference, so do exonic regions need to be used with more weight in genotype inference?

Best,
Du
